### ISSUE TITLE
Azure Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#111]
* Azure credentials crate: azure_identity (https://crates.io/crates/azure_identity)
* create Azure util file
    * azure credentials: wave-autoscale/src/util/azure/[mod.rs](http://mod.rs/)
    * azure VMSS API: wave-autoscale/src/util/azure/[azure_virtual_machine_scale_sets.rs](http://azure_virtual_machine_scale_sets.rs/)
* create Azure scaling_component file
    * scaling component: wave-autoscale/src/scaling_component/[azure_vmss_autoscaling.rs](http://azure_vmss_autoscaling.rs/)
* Target values
    * capacity 
* Configuration
    * Configuration
    ```yaml
    kind: ScalingComponent
    id: azure_vmss_autoscaling_api_server
    component_kind: azure-virtual-machine-scale-sets
    metadata:
      client_id: AZURE_CLIENT_ID
      client_secret: AZURE_CLIENT_SECRET
      tenant_id: AZURE_TENANT_ID
      subscription_id: AZURE_SUBSCRIPTION_ID
      resource_group_name: test-vmss-uniform-grp
      vm_scale_set_name: test-vmss-uniform
    ```
* `note` VMSS manually scale change if auto-scaling
* Plans and Estimated time. 
    1. check Azure documents. (https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/) (~7/27)
    2. create Azure Virtual Machine Scale Sets configuration. (~7/27)
    3. find API specifications. (~7/27)
    4. Azure credentials crate test (~8/1)
    5. Azure API test (~8/1)
    6. develop scaling component (~8/2)
    7. integration test (~8/2)
    8. PR (~8/3)
