### ISSUE TITLE
Google Cloud Functions

### ISSUE THREAD

**Issue by bryan-stclab** [STCLab-Inc/wave-autoscale#116]
* Target values
  - min instance count
  - max instance count
  - max request per instance
* Configuration
  ```yaml
  kind: ScalingComponent
  id: scaling_component_cloud_functions_instance
  component_kind: google-cloud-functions
  metadata:
    function_version: v1 # or v2
    project_name: wave-autoscale-test
    location_name: asia-northeast2
    function_name: function-1
  ```
