### ISSUE TITLE
Cool down

### ISSUE THREAD

**Issue by pueding** [STCLab-Inc/wave-autoscale#124]
During the cool-down period, the plan will not be executed.
The cool-down has been added to the plan definition.
- Add `metadata.cool_down` to the `ScalingComponentDefinition`.
- Record the `ScalingPlanner.last_plan_timestamp` when the plan is executed.
- remove code to verify that the plan has already been executed
- Move `interval` and `title` under `metadata`.
```yaml
kind: ScalingPlan
id: scaling_plan_azure_vmss_autoscaling
metadata:
  title: "Scaling Plan for Azure VMSS Autoscaling"
  cool_down: 20 # seconds
  interval: 10000 # milliseconds
plans:
  - id: scale-out-plan-1
    ...
```
