### ISSUE TITLE
Amazon EMR - EC2

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#126]
- AWS SDK EMR crate: https://crates.io/crates/aws-sdk-emr
- create AWS scaling_component file
  - scaling component: wave-autoscale/src/scaling_component/amazon_emr_ec2.rs
- Target values
  - cluster 
    - step_concurrency_level (optional, min 1 / max 256)
      (If you change a cluster's StepConcurrencyLevel to be greater than 1
       while a step is running, the ActionOnFailure parameter may not behave as you expect.)
  - instance group
    - instance_count
  - instance fleet
    - on_demand_capacity (vCPU capacity / default: 0)
    - spot_capacity (vCPU capacity / default: 0)
    - on_demand_timeout_duration_minutes (optional, min 5 / max 10,080 (7days))
    - spot_timeout_duration_minutes (optional, min 5 / max 10,080 (7days))
- Configuration
  - Configuration
    ```yaml
    kind: ScalingComponent
    id: amazon_emr_ec2_server
    component_kind: amazon-emr-ec2
    metadata:
        region: ap-northeast-1
        access_key: AWS_ACCESS_KEY
        secret_key: AWS_SECRET_KEY
        cluster_id: emr-cluster
        instance_group_id: instance-group-1
    ```
- `Note`
  - remove ManagedScalingPolicy
- Plans and Estimated time.
  - sdk test (~8/8)
  - develop scaling component (~8/8)
  - integration test (~8/9)
  - PR (~8/9)
