### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by bryan-stclab** [STCLab-Inc/wave-autoscale#132]
* Target values
  - min instance count
  - max instance count
* Configuration
  ```yaml
  kind: ScalingComponent
  id: scaling_component_azure_functions_app
  component_kind: azure-functions-app
  metadata:
    client_id: CLIENT_ID
    client_secret: CLIENT_SECRET
    tenant_id: TENANT_ID
    subscription_id: SUBSCRIPTION_ID
    resource_group_name: RESOURCE_GROUP_NAME
    app_name: APP_NAME
  ```
