### ISSUE TITLE
component target value change to JS Expression and add variable

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#154]
component target value change to JS Expression and add variable
```yml
scaling_components:
  - component_id: ec2_autoscaling_server
     desired: $desired * 2
```
- modify target value to receive characters in scaling component
- check the value of the variable in the target value, and look up the current state value data.
- save the current state value in the global variable of rquickjs
- evaluate to result value and apply

[ current state value ]
* AWS EC2 Component
  * desired
  * min
  * max
* AWS EKS Component
  * replicas
  * unavailable_replicas
  * available_replicas
  * ready_replicas
  * updated_replicas
