### ISSUE TITLE
metric definition change to collectors(vector,telegraf) format

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#157]
convert the metadata under the metric definition into Telegraf's or Vector's configuration format.

**Telegraf**
```yaml
kind: Metric
id: prometheus_metrics
collector: telegraf
metadata:
  inputs:
    prometheus:
      - urls: ["http://localhost:9090/metrics"]
        period: "10s"
        delay: "10s"
        interval: "10s"
        namepass: ["process_cpu_seconds_*"]
        tags:
          metric_id: prometheus_metrics
  outputs:
    wave-autoscale:
      tagpass:
        metric_id: prometheus_metrics
  agent:
    interval: "1s"
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    flush_interval: "1s"
```

**Vector**
```yaml
kind: Metric
id: istio_request_duration_milliseconds_sum_1m
collector: vector
metadata:
  sources:
    my_source_id_1:
      type: http_client
      query:
        "query": ['rate(istio_request_duration_milliseconds_sum{response_code="200"}[1m])']
  transforms:
    my_transforms_id_1:
      inputs: ["my_source_id_1"]
      type: remap
  sinks:
    my_sinks_id:
      type: wave-autoscale
      inputs: ["my_transforms_id_1"]
```
