### ISSUE TITLE
NetFUNNEL

### ISSUE THREAD

**Issue by bryan-stclab** [STCLab-Inc/wave-autoscale#160]
* Target values
  - max inflow
* Configuration
  ```yaml
  kind: ScalingComponent
  id: scaling_component_netfunnel_segment
  component_kind: netfunnel
  metadata:
    base_url: https://dev-api.surffy-dev.io
    authorization: authorization
    organization_id: organization_id
    tenant_id: tenant_id
    user_key: user_key
  ```
