### ISSUE TITLE
Kubernetes Patch Scaling Component

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#162]
kubernetes patch - update manifest

**ScalingComponent** (kubernetes-patch)
```yaml
kind: ScalingComponent
id: k8s_istio_vs
component_kind: kubernetes-patch
metadata:
  api_server_endpoint: "https://localhost"
```

**ScalingPlan**
```yaml
kind: ScalingPlan
id: scaling_plan_k8s_istio_vs_autoscaling
metadata:
  title: "Scaling Plan for K8S istio VirtualService Autoscaling"
  cool_down: 300 # seconds
  interval: 10000 # milliseconds
plans:
  - id: scale-out-plan-1
    description: "Scale out"
    expression: >
      get({
        metric_id: 'metric_id_1',
        name: 'name_1',
        stats: 'max',
        period_sec: 10
      }) >= 100
    priority: 1
    scaling_components:
      - component_id: k8s_istio_vs
        namespace: kube-namespace
        name: istio_vs
        manifest:
          apiVersion: networking.istio.io/v1beta1
          kind: VirtualService
          spec:
            hosts:
              - "*"
            gateways:
              - istio-gateway
            http:
              - match:
                - uri:
                     prefix: /
                   port: 9090
                 route:
                   - destination:
                        host: prometheus-community-kube-prometheus.istio-system.svc.cluster.local
                        port:
                          number: 9090
```
