### ISSUE TITLE
Cloudflare Rule Scaling Component

### ISSUE THREAD

**Issue by pueding** [STCLab-Inc/wave-autoscale#163]
- A scaling component for Cloudflare Rule
**Scaling Component**
```yaml
kind: ScalingComponent
id: cloudflare_rule
component_kind: cloudflare-rule
metadata:
  api_token:
```

**Scaling Plan**
```yaml
kind: ScalingPlan
id: scaling_plan_cloudflare_limiting
metadata:
  title: "Scaling Plan for Cloudflare"
  cool_down: 300 # seconds
  interval: 10000 # milliseconds
plans:
  - id: scale-out-plan-1
    description: "Scale out"
    expression: >
      get({
        metric_id: 'metric_id_1',
        name: 'name_1',
        stats: 'max',
        period_sec: 10
      }) >= 100
    priority: 1
    scaling_components:
      - component_id: cloudflare_rule
        # level: account or zone
        level: zone
        zone_id: 'zone_id_1'
        ruleset_id: 'ruleset_id_1'
        rule_id: 'rule_id_1'
        rule:
          action: block
          action_parameters:
            response:
              content: |-
                {
                  "success": false,
                  "error": "you have been blocked"
                }
              content_type: application/json
              status_code: 400
          description: Block when the IP address is not 1.1.1.1
          enabled: true
          expression: ip.src ne 1.1.1.1
          id: 3a03d665bac047339bb530ecb439a90d
          logging:
            enabled: true
          ref: my_ref
          position:
            before: da5e8e506c8e7877fe06cdf4c41add54
```
