### ISSUE TITLE
Console testing tool

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#198]
**plan**
 - expression test
```javascript
get({
        metric_id: 'prometheus_node_exporter_cpu_usage',
        name: 'cpu_usage',
        stats: 'max',
        period_sec: 30
      }) < 30
```
 - scaling_components test
 ```yaml
scaling_components:
  - component_id: k8s_patch
    namespace: istio-system
    name: istio-vs
    api_version: networking.istio.io/v1beta1
    kind: VirtualService
    json_patch:
     - op: add
        path: /spec/http/0/fault
        value: null
```
