### ISSUE TITLE
add metric collector - grafana

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#204]
[api server]
add metric collector - grafana
body example)
```yaml
{
  "metrics": {
    "name": "name1",
    "tags": {
      "tag1", "tag_value1"
    },
    "value": 5.12,
    "timestamp": "1700035055"
  }
}
```
