### ISSUE TITLE
ScalingPlan: sub cool down

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#244]
- sub cool down is optional
- ex. plan-1 (cool_down: 5) -> plan-1 (cool_down: 5) -> plan-2 (cool_down: 10) -> plan-1 (cool_down: 5)
```yaml
kind: ScalingPlan
id: cpu-scale-out
metadata:
  cool_down: 10 # default cool down
  interval: 1000
plans:
  - id: plan-1
    cool_down: 5 # optional cool down
    expression: |
      get({..}) < 0
    ..
  - id: plan-2
    expression: |
      get({..}) < 10
    ..
```
- ex. plan-2 (cool_down: X) -> plan-2 (cool_down: X) -> plan-2 (cool_down: 10) -> plan-2 (cool_down: X)
```yaml
kind: ScalingPlan
id: cpu-scale-out
metadata:
  interval: 1000
plans:
  - id: plan-1
    cool_down: 5 # optional cool down
    expression: |
      get({..}) < 0
    ..
  - id: plan-2
    expression: |
      get({..}) < 10
    ..
```
