### ISSUE TITLE
Scaling Plan - DynamoDB provisioned mode error

### ISSUE THREAD

**Issue by Ari-suhyeon** [STCLab-Inc/wave-autoscale#264]
DynamoDB Plan not working
![image](https://github.com/STCLab-Inc/wave-autoscale/assets/121844970/c1e83148-6de8-4c73-ad8b-92273b399a5f)

```yaml
kind: ScalingPlan
...
plans:
  - id: switch_capacity_mode_to_provisioned
    ...
    scaling_components:
      - component_id: wa_sample_component_dynamodb_table_1
        capacity_mode: PROVISIONED
        autoscaling_mode: ON
        capacity_unit: READ
        read_min_capacity: 500
        read_max_capacity: 1000
        read_target_value: 70.0
```
provisioned mode & autoscaling mode on => don't need read_capacity_units
