### ISSUE TITLE
CPU Metrics Inaccessible in Wave Autoscale Agent During AWS ASG Simulation

### ISSUE THREAD

**Issue by theo-stclab** [STCLab-Inc/wave-autoscale#281]
**Describe the bug (required)**
When simulating **AWS ASG(Auto Scaling Group)** AutoScaling using the **Wave Autoscale Agent**, CPU-related metrics (wa_agent_average_cpu_utilization, wa_agent_cpu_usage) are not accessible. 
Other metrics are retrieved successfully, but attempting to use CPU-related metrics results in the following error message:
![image](https://github.com/STCLab-Inc/wave-autoscale/assets/164296854/d2bd5591-75b1-461e-9b56-bd2269a54342)

**Environments (optional)**
- ScalingPlan
```yaml
# Other settings are omitted
...

variables:
  max_cpu_usage: |
    get({
      metric_id: 'metric_nginx',
      name: 'wa_agent_cpu_usage',
      stats: 'max',
      period_sec: 30
    })

# Remaining settings are omitted
...

```
- Wave Autoscale Agent Version: dev
- Operating System: Ubuntu 22.04 LTS
- EC2 Instance Type: t2.nano
- EC2 AMI: Ubuntu(22.04 LTS)

**Screenshots (optional)**
- WAA Metrics
![image](https://github.com/STCLab-Inc/wave-autoscale/assets/164296854/638837c3-46d2-41ec-8142-4f8f9e9eef66)
