### ISSUE TITLE
AWS ECS Service

### ISSUE THREAD

**Issue by pueding** [STCLab-Inc/wave-autoscale#76]
* Target values
  - desired count
* Configuration
  - Definition
  ```yaml
  kind: ScalingComponent
  id: aws_ecs_ec2_service_scaling_server
  component_kind: amazon-ecs
  metadata:
    region: ap-northeast-3
      access_key: [AWS_ACCEESS_KEY_ID]
      secret_key: [AWS_SECRET_KEY_ID]
      cluster_name: wave-test-cluster10
      service_name: wave-test-cluster10-service3
  ```
  - Trigger
  ```yaml
  kind: ScalingPlan
  id: scaling_plan_ecs_ec2_service_scaling
  title: "Scaling Plan for ECS Service Scaling"
  plans:
    - id: scale-in-plan-1
      description: "Scale in if CPU usage is less than 1%."
      expression: "cloudwatch_cpu_max < 1"
      priority: 1
      scaling_components:
        - component_id: aws_ecs_ec2_service_scaling_server
          desired: 1
  ```
