### ISSUE TITLE
Read variables from other sources such as env

### ISSUE THREAD

**Issue by pueding** [STCLab-Inc/wave-autoscale#85]
```yaml
access_key: [ENV:AWS_ACCESS_KEY_ID]
secret_key: [ENV:AWS_SECRET_ACCESS_KEY]
access_key: [SECRETS_MANAGER:AWS_ACCESS_KEY_ID]
secret_key: [SECRETS_MANAGER:AWS_SECRET_ACCESS_KEY]
```
