### ISSUE TITLE
Amazon DynamoDB

### ISSUE THREAD

**Issue by bryan-stclab** [STCLab-Inc/wave-autoscale#97]
* Target values
  - capacity mode
  - autoscaling mode
  - capacity unit
  - read capacity units
  - write capacity units
  - read target value
  - read min capacity
  - read max capacity
  - write target value
  - write min capacity
  - write max capacity
* Configuration
  ```yaml
  kind: ScalingComponent
  id: dynamodb-table
  component_kind: amazon-dynamodb
  metadata:
    region: ap-northeast-2
    access_key: [AWS_ACCEESS_KEY_ID]
    secret_key: [AWS_SECRET_KEY_ID]
    table_name: test-dynamodb-table
  ```
  - Trigger
  ```yaml
  kind: ScalingPlan
  id: scaling_plan_dynamodb-table
  title: "Scaling Plan for DynamoDB Table"
  plans:
    - id: switch-capacity_mode-to-on-demand
      description: "Switch capacity mode to on-demand if consumed write capacity units value is greater than 10."
      # JavaScript expression that returns a boolean value.
      expression: "cloudwatch_consumed_write_capacity_units_cnt >= 10"
      # Higher priority values will be checked first.
      priority: 1
      scaling_components:
        - component_id: scaling_component_dynamodb-table
          # JavaScript expression that returns an integer.
          capacity_mode: PAY_PER_REQUEST
    - id: switch-capacity_mode-to-provisioned
      description: "Switch capacity mode to on-demand if consumed write capacity units value is greater than 100."
      # JavaScript expression that returns a boolean value.
      expression: "cloudwatch_consumed_write_capacity_units_cnt >= 100"
      priority: 2
      scaling_components:
        - component_id: scaling_component_dynamodb_table
          # JavaScript expression that returns an integer.
          capacity_mode: PAY_PER_REQUEST
          autoscaling_mode: "PROVISIONED"
          capacity_unit: "READ_WRITE"
          read_min_capacity: 5
          read_max_capacity: 10
          read_target_value: 60.0
          write_min_capacity: 5
          write_max_capacity: 10
          write_target_value: 80.0
  ```
